@entryPoint = http://localhost:4200

@accessToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo1LCJub20iOiJ0ZXN0NCIsInByZW5vbSI6InVzZXI0IiwiZW1haWwiOiJ0ZXN0NEBnbWFpbC5jb20iLCJyb2xlIjoxfSwiaWF0IjoxNzA0MDA4NDg4LCJleHAiOjE3MDQwOTQ4ODh9._qhY5XJ4LWiYKt5h2yUvcKscyq9ChJR9kr1ShiNag_A
@refreshToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo1LCJub20iOiJ0ZXN0NCIsInByZW5vbSI6InVzZXI0IiwiZW1haWwiOiJ0ZXN0NEBnbWFpbC5jb20iLCJyb2xlIjoxfSwiaWF0IjoxNzA0MDA4NDg4LCJleHAiOjE3MDQxODEyODh9.yDd8Iv3DeO9vVfE8FizXqaVI3IwMZAnLJs_H5OVh5Ac

#& -----------------------------------------------
#~ ------------------------------------------ USER
#& -----------------------------------------------

#~ ------------------------ doSignUp
###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "nom": "test4",
    "prenom": "user4",
    "email": "test4@gmail.com",
    "mot_de_passe": "N6y$Ozddzt=1aa",
    "mot_de_passe_confirm": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignIn
###
POST {{entryPoint}}/signin
Content-Type: application/json

{
  "email": "test@gmail.com",
  "mot_de_passe": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignOut
###
GET {{entryPoint}}/signout
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ fetchOneUser
###
GET {{entryPoint}}/users/3
Content-Type: application/json
{{accessToken}}


#^ ------------------------ updateUser
###
PATCH {{entryPoint}}/users/1
Content-Type: application/json
{{accessToken}}

{
    "nom": "Yusssmdsdzxsssedooooeeee"
}


#^ ------------------------ deleteUser
###
DELETE {{entryPoint}}/users/2
Content-Type: application/json
{{accessToken}}

#^ ------------------------ refreshToken
###
POST {{entryPoint}}/refreshToken
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ Training

#^ ------------------------ createTraining
###
POST {{entryPoint}}/training
Content-Type: application/json
{{accessToken}}

{
    "titre": "anaerobie",
    "detail": " moins difficile"

}


#^ ------------------------ fetchAllTraining
###
GET {{entryPoint}}/training
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateTraining
###
PATCH {{entryPoint}}/training/1
Content-Type: application/json
{{accessToken}}

{
    "titre": "100 pompes",
    "detail": "bla bla bla "
}

#^ ------------------------ deleteTraining
###
DELETE {{entryPoint}}/training/3
Content-Type: application/json
{{accessToken}}



#^ ------------------------ Type

#^ ------------------------ createType
###
POST {{entryPoint}}/type
Content-Type: application/json
{{accessToken}}

{
    "titre": "abs"

}


#^ ------------------------ fetchAllType
###
GET {{entryPoint}}/type
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateType
###
PATCH {{entryPoint}}/type/3
Content-Type: application/json
{{accessToken}}

{
    "titre": "abs!"
}

#^ ------------------------ deleteType
###
DELETE {{entryPoint}}/type/1
Content-Type: application/json
{{accessToken}}




#^ ------------------------ Exercice

#^ ------------------------ createExercice
###
POST {{entryPoint}}/exercice
Content-Type: application/json
{{accessToken}}

{
    "titre": "plank",
    "detail": "pompes classic ",
    "illustration": "svg"
}


#^ ------------------------ fetchAllExercice
###
GET {{entryPoint}}/exercice
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateExercice
###
PATCH {{entryPoint}}/exercice/1
Content-Type: application/json
{{accessToken}}

{
    "titre": "pull up"
}

#^ ------------------------ deleteExercice
###
DELETE {{entryPoint}}/exercice/3
Content-Type: application/json
{{accessToken}}


#^ ------------------------ Materiel

#^ ------------------------ createMateriel
###
POST {{entryPoint}}/materiel
Content-Type: application/json
{{accessToken}}

{
    "nom": "velo"
}


#^ ------------------------ fetchAllMateriel
###
GET {{entryPoint}}/materiel
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateMateriel
###
PATCH {{entryPoint}}/materiel/1
Content-Type: application/json
{{accessToken}}

{
    "nom": "slam ball"
}

#^ ------------------------ deleteMateriel
###
DELETE {{entryPoint}}/materiel/1
Content-Type: application/json
{{accessToken}}




#^ ------------------------ Niveau

#^ ------------------------ createNiveau
###
POST {{entryPoint}}/niveau
Content-Type: application/json
{{accessToken}}

{
    "description": "advanced",
    "max_rep": 60
}



#^ ------------------------ fetchAllNiveau
###
GET {{entryPoint}}/niveau
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateNiveau
###
PATCH {{entryPoint}}/niveau/1
Content-Type: application/json
{{accessToken}}

{
    "description": "débutant",
    "max_rep": 8
}

#^ ------------------------ deleteNiveau
###
DELETE {{entryPoint}}/niveau/3
Content-Type: application/json
{{accessToken}}






#^ ------------------------ User Has Training

#^ ------------------------ createUserHasTraining
###
POST {{entryPoint}}/user/5/training/4
Content-Type: application/json
{{accessToken}}



#^ ------------------------ fetchAll Train by User
###
GET {{entryPoint}}/user/5/userHasTraining
Content-Type: application/json
{{accessToken}}


#^ ------------------------ delete Training By User
###
DELETE {{entryPoint}}/user/5/training/7
Content-Type: application/json
{{accessToken}}

