@entryPoint = http://localhost:4200

@accessToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJub20iOiJ0ZXN0MiIsInByZW5vbSI6InVzZXJhZG1pbiIsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicm9sZSI6MX0sImlhdCI6MTcwNTY3MzU4NCwiZXhwIjoxNzA1NzU5OTg0fQ.tyqDsR39mAFFkr8Q_ie2Pm7i-HbzMjlRO2BJdVH_zUY
@refreshToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJub20iOiJ0ZXN0MiIsInByZW5vbSI6InVzZXJhZG1pbiIsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicm9sZSI6MX0sImlhdCI6MTcwNTY3MzU4NCwiZXhwIjoxNzA1ODQ2Mzg0fQ.HCHd3S01hJub4Cww7H7duy9V7uf0SE-mu7TbWnX3Qp0

#& -----------------------------------------------
#~ ------------------------------------------ USER
#& -----------------------------------------------

#~ ------------------------ doSignUp
###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "nom": "test2",
    "prenom": "useradmin",
    "email": "test4@gmail.com",
    "mot_de_passe": "N6y$Ozddzt=1aa",
    "mot_de_passe_confirm": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignIn
###
POST {{entryPoint}}/signin
Content-Type: application/json

{
  "email": "testadmin@gmail.com",
  "mot_de_passe": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignOut
###
GET {{entryPoint}}/signout
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ fetchOneUser
###
GET {{entryPoint}}/users/3
Content-Type: application/json
{{accessToken}}


#^ ------------------------ updateUser
###
PATCH {{entryPoint}}/users/5
Content-Type: application/json
{{accessToken}}

{
    "nom": "Yus"
}


#^ ------------------------ deleteUser
###
DELETE {{entryPoint}}/users/2
Content-Type: application/json
{{accessToken}}

#^ ------------------------ refreshToken
###
POST {{entryPoint}}/refreshToken
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ Training

#^ ------------------------ createTraining  ADMIN
###
POST {{entryPoint}}/training
Content-Type: application/json
{{accessToken}}

{
    "titre": "1pushup",
    "detail": " testtt"

}


#^ ------------------------ fetchAllTraining
###
GET {{entryPoint}}/training
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateTraining  ADMIN
###
PATCH {{entryPoint}}/training/2
Content-Type: application/json
{{accessToken}}

{
    "titre": "100 pompes",
    "detail": "bla bla bla "
}

#^ ------------------------ deleteTraining  ADMIN
###
DELETE {{entryPoint}}/training/3
Content-Type: application/json
{{accessToken}}



#^ ------------------------ Type

#^ ------------------------ createType  ADMIN
###
POST {{entryPoint}}/type
Content-Type: application/json
{{accessToken}}

{
    "titre": "pushupObjectif"

}


#^ ------------------------ fetchAllType
###
GET {{entryPoint}}/type
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateType  ADMIN
###
PATCH {{entryPoint}}/type/3
Content-Type: application/json
{{accessToken}}

{
    "titre": "abs!"
}

#^ ------------------------ deleteType  ADMIN
###
DELETE {{entryPoint}}/type/1
Content-Type: application/json
{{accessToken}}




#^ ------------------------ Exercice

#^ ------------------------ createExercice  ADMIN
###
POST {{entryPoint}}/exercice
Content-Type: application/json
{{accessToken}}

{
    "titre": "10pushup",
    "detail": "test",
    "illustration": "svg"
}


#^ ------------------------ fetchAllExercice
###
GET {{entryPoint}}/exercice
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateExercice  ADMIN
###
PATCH {{entryPoint}}/exercice/1
Content-Type: application/json
{{accessToken}}

{
    "titre": "pull up"
}

#^ ------------------------ deleteExercice  ADMIN
###
DELETE {{entryPoint}}/exercice/3
Content-Type: application/json
{{accessToken}}


#^ ------------------------ Materiel

#^ ------------------------ createMateriel ADMIN
###
POST {{entryPoint}}/materiel
Content-Type: application/json
{{accessToken}}

{
    "nom": "haltères"
}


#^ ------------------------ fetchAllMateriel
###
GET {{entryPoint}}/materiel
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateMateriel ADMIN
###
PATCH {{entryPoint}}/materiel/1
Content-Type: application/json
{{accessToken}}

{
    "nom": "slam ball"
}

#^ ------------------------ deleteMateriel  ADMIN
###
DELETE {{entryPoint}}/materiel/1
Content-Type: application/json
{{accessToken}}




#^ ------------------------ Niveau

#^ ------------------------ createNiveau  ADMIN
###
POST {{entryPoint}}/niveau
Content-Type: application/json
{{accessToken}}

{
    "description": "casual-3",
    "max_rep": 300
}



#^ ------------------------ fetchAllNiveau
###
GET {{entryPoint}}/niveau
Content-Type: application/json
{{accessToken}}

#^ ------------------------ updateNiveau  ADMIN
###
PATCH {{entryPoint}}/niveau/4
Content-Type: application/json
{{accessToken}}

{
    "description": "débutant",
    "max_rep": 8
}

#^ ------------------------ deleteNiveau  ADMIN
###
DELETE {{entryPoint}}/niveau/4
Content-Type: application/json
{{accessToken}}






#^ ------------------------ User Has Training

#^ ------------------------ createUserHasTraining
###
POST {{entryPoint}}/user/1/training/2
Content-Type: application/json
{{accessToken}}



#^ ------------------------ fetchAll Train by User
###
GET {{entryPoint}}/user/1/userHasTraining
Content-Type: application/json
{{accessToken}}


#^ ------------------------ delete Training By User
###
DELETE {{entryPoint}}/user/5/training/7
Content-Type: application/json
{{accessToken}}



#^ ------------------------ Training has type

#^ ------------------------ create training has type  ADMIN
###
POST {{entryPoint}}/training/1/type/1
Content-Type: application/json
{{accessToken}}



#^ ------------------------ fetchAll Training by type
###
GET {{entryPoint}}/trainingByType/type/1
Content-Type: application/json
{{accessToken}}


#^ ------------------------ delete Training Has Type  ADMIN
###
DELETE {{entryPoint}}/trainingHasType/6
Content-Type: application/json
{{accessToken}}




#^ ------------------------ Training has Exercice

#^ ------------------------ create training has exercice  ADMIN
###
POST {{entryPoint}}/training/2/exercice/2
Content-Type: application/json
{{accessToken}}



#^ ------------------------ fetchAll Exercice By Training
###
GET {{entryPoint}}/trainingHasExercice/training/2
Content-Type: application/json
{{accessToken}}


#^ ------------------------ delete exercice in training  ADMIN   
###
DELETE {{entryPoint}}/trainingHasExercice/training/4/exercice/7
Content-Type: application/json
{{accessToken}} 



#^ ------------------------ Exercice has Niveau

#^ ------------------------ create Exercice has niveau
###
POST {{entryPoint}}/niveau/1/exercice/2/user/1
Content-Type: application/json
{{accessToken}}

#^ ------------------------ VALIDATE niveau
###
PATCH {{entryPoint}}/niveau/1/exercice/2/user/2
Content-Type: application/json
{{accessToken}}



#^ ------------------------ niveau down
###
PATCH {{entryPoint}}/niveau/1/exercice/2/user/1/down
Content-Type: application/json
{{accessToken}}



#^ ------------------------ CHECK niveau for exercice by user
###
GET {{entryPoint}}/exercicehasniveau/exercice/2/user/2
Content-Type: application/json
{{accessToken}} 


#^ ------------------------ delete niveau for exercice by user
###
DELETE {{entryPoint}}/exercicehasniveau/exercice/2/user/1
Content-Type: application/json
{{accessToken}} 

#^ ------------------------ TEST
###
POST {{entryPoint}}/exerciceHasSerie/user/2/exercice/2
Content-Type: application/json
{{accessToken}} 